rw:
  separation:
    ds:
      defaultDs: ds0
    masterDsConfigs:
      - dsName: ds0
        driverClassName: com.mysql.jdbc.Driver
        jdbcUrl: jdbc:mysql://ip:port/myutilproject0?characterEncoding=GBK&useSSL=false
        username: root
        password: wanyang@wms
    slaverDsConfigs:
      - dsName: ds1
        masterDsName: ds0
        driverClassName: com.mysql.jdbc.Driver
        jdbcUrl: jdbc:mysql://ip:port/myutilproject1?characterEncoding=GBK&useSSL=false
        username: root
        password: wanyang@wms



logging:
  level:
    root: debug
